const cfg=window.LZ_CONFIG;let cart=JSON.parse(localStorage.getItem('lz-cart')||'[]');let activeProduct=null;let chosenSize=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
$('#announcement').textContent=cfg.brand.announcement;$('#footerTagline').textContent=cfg.brand.tagline;$('#igLink').href=cfg.brand.instagram;$('#ttLink').href=cfg.brand.tiktok;
const money=n=>new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(n);
function renderProducts(filter='todos'){const list=filter==='todos'?cfg.products:cfg.products.filter(p=>p.category===filter);$('#productGrid').innerHTML=list.map(p=>`<article class="product-card" data-id="${p.id}"><span class="product-badge">${p.badge}</span><div class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy"></div><div class="product-meta"><div><h3>${p.name}</h3><p>${p.color}</p></div><div class="product-price">${money(p.price)}</div></div></article>`).join('');$$('.product-card').forEach(c=>c.onclick=()=>openProduct(c.dataset.id));}
renderProducts();
$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts(b.dataset.filter)});
$$('[data-scroll-filter]').forEach(b=>b.onclick=()=>{const f=b.dataset.scrollFilter;$('#catalogo').scrollIntoView();setTimeout(()=>{$(`.filter[data-filter="${f}"]`).click()},350)});
function openProduct(id){activeProduct=cfg.products.find(p=>p.id===id);chosenSize=null;$('#modalImage').src=activeProduct.image;$('#modalName').textContent=activeProduct.name;$('#modalBadge').textContent=activeProduct.badge;$('#modalColor').textContent=activeProduct.color;$('#modalPrice').textContent=money(activeProduct.price);$('#modalDesc').textContent=activeProduct.description;$('#sizeGrid').innerHTML=activeProduct.sizes.map(s=>`<button class="size-btn" data-size="${s}">${s}</button>`).join('');$$('.size-btn').forEach(b=>b.onclick=()=>{$$('.size-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');chosenSize=b.dataset.size});$('#productModal').classList.add('open');$('#productModal').setAttribute('aria-hidden','false');$('#backdrop').classList.add('show');document.body.style.overflow='hidden'}
function closeModal(){$('#productModal').classList.remove('open');$('#backdrop').classList.remove('show');document.body.style.overflow=''}
$('#modalClose').onclick=closeModal;
$('#modalAdd').onclick=()=>{if(!chosenSize){$('#modalAdd').textContent='ESCOLHA UM TAMANHO ↑';setTimeout(()=>$('#modalAdd').textContent='ADICIONAR AO CARRINHO',1300);return}cart.push({...activeProduct,size:chosenSize,cartId:Date.now()});saveCart();closeModal();openCart()};
function saveCart(){localStorage.setItem('lz-cart',JSON.stringify(cart));renderCart()}
function renderCart(){$('#cartCount').textContent=cart.length;$('#cartEmpty').style.display=cart.length?'none':'block';$('#cartItems').innerHTML=cart.map(i=>`<div class="cart-item"><img src="${i.image}"><div><h4>${i.name}</h4><small>${i.size} · ${i.color}</small><p>${money(i.price)}</p></div><button data-remove="${i.cartId}">×</button></div>`).join('');$('#cartTotal').textContent=money(cart.reduce((a,b)=>a+b.price,0));$$('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(i=>i.cartId!=b.dataset.remove);saveCart()})}
renderCart();
function openCart(){$('#cartDrawer').classList.add('open');$('#backdrop').classList.add('show');document.body.style.overflow='hidden'}function closeCart(){$('#cartDrawer').classList.remove('open');$('#backdrop').classList.remove('show');document.body.style.overflow=''}
$('#cartBtn').onclick=openCart;$('#closeCart').onclick=closeCart;$('#backdrop').onclick=()=>{closeCart();closeModal()};
$('#newsletterForm').onsubmit=e=>{e.preventDefault();$('#newsletterNote').textContent='Você entrou no Inner Circle. Agora ficou perigoso 😮‍💨';e.target.reset()};
function openSearch(){$('#searchOverlay').classList.add('open');setTimeout(()=>$('#searchInput').focus(),200);searchProducts('')}function closeSearch(){$('#searchOverlay').classList.remove('open');$('#searchInput').value=''}
$('#searchBtn').onclick=openSearch;$('#closeSearch').onclick=closeSearch;$('#searchInput').oninput=e=>searchProducts(e.target.value);
function searchProducts(q){let list=cfg.products.filter(p=>(p.name+' '+p.color).toLowerCase().includes(q.toLowerCase()));$('#searchResults').innerHTML=list.map(p=>`<div class="search-item" data-search-id="${p.id}"><img src="${p.image}"><p>${p.name} — ${money(p.price)}</p></div>`).join('');$$('[data-search-id]').forEach(x=>x.onclick=()=>{closeSearch();openProduct(x.dataset.searchId)})}
const obs=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});$$('.reveal').forEach(el=>obs.observe(el));
window.addEventListener('keydown',e=>{if(e.key==='Escape'){closeCart();closeModal();closeSearch()}});
