create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text unique not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.newsletter_subscribers enable row level security;
-- Não crie policy pública. As APIs usam a service role somente no servidor.
