
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let cfg=null,editingId=null,gh=false;
async function api(u,o={}){const r=await fetch(u,{...o,headers:{'Content-Type':'application/json',...(o.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Erro');return d}
async function boot(){const me=await api('/api/admin/me');if(me.authenticated){showApp();setGh(me);cfg=await api('/api/admin/config');renderAll()}else showLogin()}
function showLogin(){$('#loginView').classList.remove('hidden');$('#appView').classList.add('hidden')}function showApp(){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden')}
function setGh(me){gh=!!me.githubConfigured;const e=$('#githubStatus');e.textContent=gh?`● conectado · ${me.repo}`:'● GitHub não configurado';e.className='status '+(gh?'ok':'bad');$('#publishHelp').textContent=gh?'Ao publicar, o painel atualiza config.json no GitHub. A Vercel recebe o commit e redeploya sozinha.':'Configure GITHUB_TOKEN, GITHUB_OWNER e GITHUB_REPO nas variáveis da Vercel para ativar o automático.'}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({password:$('#password').value})});const me=await api('/api/admin/me');showApp();setGh(me);cfg=await api('/api/admin/config');renderAll()}catch(x){$('#loginMsg').textContent=x.message}}
$('#logoutBtn').onclick=async()=>{await api('/api/admin/logout',{method:'POST'});location.reload()}
function renderAll(){renderStats();renderProducts();renderSite()}function renderStats(){const p=cfg.products||[],v=p.filter(x=>x.visible!==false);$('#stats').innerHTML=[['Produtos',v.length],['Masculino',v.filter(x=>x.gender==='masculino').length],['Feminino',v.filter(x=>x.gender==='feminino').length],['Destaques',v.filter(x=>x.featured).length]].map(x=>`<div class="stat"><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join('')}
function renderProducts(q=''){const l=cfg.products.filter(p=>`${p.name} ${p.type} ${p.gender} ${p.color}`.toLowerCase().includes(q.toLowerCase()));$('#productList').innerHTML=l.map(p=>`<div class="product-row"><img src="../${p.image.replace('./','')}"><div><h4>${p.name}</h4><p>${p.type} · ${p.gender} · ${p.color} · €${Number(p.price).toFixed(2).replace('.',',')}</p></div><span class="badge">${p.visible===false?'OCULTO':p.featured?'DESTAQUE':'ATIVO'}</span><div class="row-actions"><button data-edit="${p.id}">Editar</button><button data-toggle="${p.id}">${p.visible===false?'Mostrar':'Ocultar'}</button><button class="danger" data-del="${p.id}">Excluir</button></div></div>`).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));$$('[data-toggle]').forEach(b=>b.onclick=()=>{const p=cfg.products.find(x=>x.id===b.dataset.toggle);p.visible=p.visible===false;renderAll()});$$('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('Excluir?')){cfg.products=cfg.products.filter(x=>x.id!==b.dataset.del);renderAll()}})}
$('#productSearch').oninput=e=>renderProducts(e.target.value);$('#addProductBtn').onclick=()=>openEditor(null);
function esc(s=''){return String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;')}
function openEditor(id){editingId=id;const p=id?cfg.products.find(x=>x.id===id):{id:'',name:'',type:'camiseta',gender:'masculino',price:34.99,color:'',image:'',description:'',sizes:['S','M','L','XL'],visible:true,featured:false};$('#editorTitle').textContent=id?'Editar produto':'Novo produto';$('#productForm').innerHTML=`<label>ID<input name="id" value="${esc(p.id)}" ${id?'readonly':''}></label><label>Nome<input name="name" value="${esc(p.name)}"></label><label>Tipo<select name="type"><option ${p.type==='camiseta'?'selected':''}>camiseta</option><option ${p.type==='moletom'?'selected':''}>moletom</option></select></label><label>Público<select name="gender"><option ${p.gender==='masculino'?'selected':''}>masculino</option><option ${p.gender==='feminino'?'selected':''}>feminino</option></select></label><label>Preço<input name="price" type="number" step=".01" value="${p.price}"></label><label>Cor<input name="color" value="${esc(p.color)}"></label><label class="full">Imagem<input name="image" id="imgPath" value="${esc(p.image)}"></label><label class="full">Upload<input id="imgUpload" type="file" accept="image/png,image/jpeg,image/webp"></label><div class="full"><img class="image-preview" id="imgPreview" src="../${String(p.image).replace('./','')}"></div><label class="full">Descrição<textarea name="description">${esc(p.description||'')}</textarea></label><label class="full">Tamanhos<input name="sizes" value="${esc((p.sizes||[]).join(', '))}"></label><label class="check"><input name="visible" type="checkbox" ${p.visible!==false?'checked':''}> Visível</label><label class="check"><input name="featured" type="checkbox" ${p.featured?'checked':''}> Destaque</label><div class="full"><button class="primary">SALVAR PRODUTO</button></div>`;$('#editorModal').classList.remove('hidden');$('#imgPath').oninput=e=>$('#imgPreview').src=e.target.value;$('#imgUpload').onchange=uploadImage}
async function uploadImage(e){const f=e.target.files[0];if(!f)return;if(!gh)return alert('Configure o GitHub primeiro.');const rd=new FileReader();rd.onload=async()=>{try{const o=await api('/api/admin/upload',{method:'POST',body:JSON.stringify({filename:f.name,data:rd.result})});$('#imgPath').value=o.path;$('#imgPreview').src=rd.result}catch(x){alert(x.message)}};rd.readAsDataURL(f)}
$('#closeEditor').onclick=()=>$('#editorModal').classList.add('hidden');$('#productForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),id=String(f.get('id')).trim().toLowerCase().replace(/[^a-z0-9_-]+/g,'-'),p={id,name:f.get('name'),type:f.get('type'),gender:f.get('gender'),price:Number(f.get('price')),color:f.get('color'),image:f.get('image'),description:f.get('description'),sizes:String(f.get('sizes')).split(',').map(x=>x.trim()).filter(Boolean),visible:f.get('visible')==='on',featured:f.get('featured')==='on'};if(editingId){cfg.products[cfg.products.findIndex(x=>x.id===editingId)]=p}else{if(cfg.products.some(x=>x.id===id))return alert('ID já existe');cfg.products.push(p)}$('#editorModal').classList.add('hidden');renderAll()}
function renderSite(){const b=cfg.brand,s=cfg.settings;$('#siteForm').innerHTML=`<div class="field"><label>Nome da loja</label><input data-path="brand.storeName" value="${esc(b.storeName)}"></div><div class="field"><label>Ano</label><input data-path="brand.year" value="${esc(b.year)}"></div><div class="field full"><label>Aviso do topo</label><input data-path="brand.announcement" value="${esc(b.announcement)}"></div><div class="field"><label>Kicker</label><input data-path="brand.heroKicker" value="${esc(b.heroKicker)}"></div><div class="field"><label>Título catálogo</label><input data-path="settings.catalogTitle" value="${esc(s.catalogTitle)}"></div><div class="field full"><label>Título principal (use \\n)</label><textarea data-path="brand.heroTitle">${esc(b.heroTitle)}</textarea></div><div class="field full"><label>Descrição principal</label><textarea data-path="brand.heroText">${esc(b.heroText)}</textarea></div><label class="check"><input type="checkbox" data-check="settings.showAnnouncement" ${s.showAnnouncement?'checked':''}> Mostrar aviso</label><label class="check"><input type="checkbox" data-check="settings.showCursorGlow" ${s.showCursorGlow!==false?'checked':''}> Luz do cursor</label>`;$$('[data-path]').forEach(e=>e.oninput=()=>setPath(e.dataset.path,e.value));$$('[data-check]').forEach(e=>e.onchange=()=>setPath(e.dataset.check,e.checked))}
function setPath(path,v){const a=path.split('.');let x=cfg;for(let i=0;i<a.length-1;i++)x=x[a[i]];x[a.at(-1)]=v}
$$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.page));function go(p){$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$$('.page').forEach(x=>x.classList.toggle('active',x.dataset.pagePanel===p));$('#pageTitle').textContent={dashboard:'Visão geral',products:'Produtos',site:'Site',publish:'Publicação'}[p]}
$('#publishBtn').onclick=async()=>{const m=$('#publishMsg');m.textContent='Publicando...';try{const o=await api('/api/admin/save',{method:'POST',body:JSON.stringify({config:cfg})});m.textContent=o.message}catch(x){m.textContent=x.message}}
$('#backupBtn').onclick=()=>{const a=document.createElement('a'),b=new Blob([JSON.stringify(cfg,null,2)],{type:'application/json'});a.href=URL.createObjectURL(b);a.download='lz-config-backup.json';a.click()}
boot();
